### ISSUE TITLE
erreur rencontrée lors de la première utilisation de WinClean

### ISSUE THREAD

**Issue by clojos** [5cover/WinClean#2]
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Ookii.Dialogs.Wpf.NativeMethods.DeactivateActCtx(UInt32 dwFlags, IntPtr lpCookie)
   at Ookii.Dialogs.Wpf.ComCtlv6ActivationContext.Dispose(Boolean disposing)
   at Ookii.Dialogs.Wpf.ComCtlv6ActivationContext.Dispose()
   at Ookii.Dialogs.Wpf.TaskDialog.ShowDialog(IntPtr owner)
   at Ookii.Dialogs.Wpf.TaskDialog.Show()
   at Scover.WinClean.Presentation.Dialogs.Dialog.Show() in C:\Users\Scover\source\repos\WinClean\Presentation\Dialogs\Dialog.cs:line 143
   at Scover.WinClean.Presentation.ScriptExecution.ScriptExecutionWizard.ShowScriptExecutionProgressDialog() in C:\Users\Scover\source\repos\WinClean\Presentation\ScriptExecutionWizard.cs:line 278
   at Scover.WinClean.Presentation.ScriptExecution.ScriptExecutionWizard.Execute() in C:\Users\Scover\source\repos\WinClean\Presentation\ScriptExecutionWizard.cs:line 97
   at Scover.WinClean.Presentation.Windows.MainWindow.ButtonExecuteScriptsClick(Object sender, RoutedEventArgs e) in C:\Users\Scover\source\repos\WinClean\Presentation\Windows\MainWindow.xaml.cs:line 131
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by 5cover** [comment]
Pouvez-vous donner plus de détails?
Utilisez-vous la version portable?
Quels scripts avez-vous exécuté? 
L'erreur a-t-elle été précédée par une autre erreur?

**Comment by 5cover** [comment]
Closing this due to lack of information.
