### ISSUE TITLE
An unhandled exception ocurr

### ISSUE THREAD

**Issue by JadranR** [5cover/WinClean#4]
System.AggregateException: One or more errors occurred. (The type initializer for 'System.Management.Automation.ExperimentalFeature' threw an exception.)
 ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.ExperimentalFeature' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.Configuration.PowerShellConfig' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at System.Management.Automation.Configuration.PowerShellConfig..ctor()
   at System.Management.Automation.Configuration.PowerShellConfig..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExperimentalFeature..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Scover.WinClean.BusinessLogic.Scripts.Hosts.PowerShell.ExecuteCode(String code, String scriptName, TimeSpan timeout, HungScriptCallback keepRunningElseKill, CancellationToken cancellationToken) in C:\Users\Scover\source\repos\WinClean\BusinessLogic\Scripts\Hosts\PowerShell.cs:line 22
   at Scover.WinClean.BusinessLogic.ScriptExecutor.<>c__DisplayClass6_0.<ExecuteScriptsAsync>b__0() in C:\Users\Scover\source\repos\WinClean\BusinessLogic\ScriptExecutor.cs:line 38
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Scover.WinClean.BusinessLogic.ScriptExecutor.ExecuteScriptsAsync(IReadOnlyList`1 scripts, HungScriptCallback keepRunningElseKill) in C:\Users\Scover\source\repos\WinClean\BusinessLogic\ScriptExecutor.cs:line 31
   at Scover.WinClean.Presentation.ScriptExecution.ScriptExecutionWizard.ExecuteScriptsAsync() in C:\Users\Scover\source\repos\WinClean\Presentation\ScriptExecutionWizard.cs:line 208
   at Scover.WinClean.Presentation.ScriptExecution.ScriptExecutionWizard.<>c__DisplayClass10_0.<<ShowScriptExecutionProgressDialog>b__6>d.MoveNext() in C:\Users\Scover\source\repos\WinClean\Presentation\ScriptExecutionWizard.cs:line 275
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by 5cover** [comment]
Seems to be a bug with the Microsoft PowerShell package. I was unable to reproduce it. I decided to stop using it due to other  issues. I don't know what caused this exception precisely, but it souldn't occur in 1.2.1.
