### ISSUE TITLE
Winclean - Unhandled exception

### ISSUE THREAD

**Issue by rakibxdev** [5cover/WinClean#8]
Os: Windows11

System.Management.ManagementException: Initialization failure 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Scover.WinClean.Services.OperatingSystem.get_SystemRestoreEligibleDrives()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Scover.WinClean.ViewModel.Pages.Page1ViewModel..ctor()
   at Scover.WinClean.ViewModel.Windows.ScriptExecutionWizardViewModel..ctor(IList`1 executionInfos)
   at Scover.WinClean.ViewModel.Windows.MainViewModel.<.ctor>b__3_7()
   at CommunityToolkit.Mvvm.Input.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by 5cover** [comment]
Seems like WMI failed to initialize
Does this happen consistently when clicking the "Execute scripts" button or did it happen only once?

**Comment by rakibxdev** [comment]
consistently

**Comment by 5cover** [comment]
What's failing precisely is the piece of code that detects which drives you have that support restore points.
What drives to you have? (such as C:, D: ...)

**Comment by aightbet69** [comment]
Hi, I have the same issue. I'm using "C:". Can you help me?

**Comment by 5cover** [comment]
According to my tests, the issue only comes up when WinClean is ran without admin privileges.
Is that right?
(sorry about the delay, btw)

**Comment by 5cover** [comment]
As of version 1.3.0, this issue only happens when the app is ran without admin privileges (as far as I've found)
The next version will replace the current restore point interface by a simple button to open *SystemPropertiesProtection.exe*
